### ISSUE TITLE
formio copy does not copy "Actions" or "Access" values

### ISSUE THREAD

**Issue by sgronblo** [formio/cli#11]
I tried running:

`formio copy form --key=MY_API_KEY SRCHOST/SRCFORM DSTHOST/DSTFORM`

The copy is successful. However the "Actions" and the "Access" values are not copied over to the form's copy.

**Comment by jeriah-formio** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
