### ISSUE TITLE
Error: unexpected server response (426) when trying to use command line binding

### ISSUE THREAD

**Issue by zpbd** [formio/cli#12]
After running `formio bind [method] [url]` and being asked to enter credentials, after seeing the `Authentication successful` message, I simply get `Error: unexpected server response (426)`

The parameters being used are:

`bind POST https://xxxxxxxxxxxx.form.io/test/submission`

Which should simply print out the raw JSON according to the [documentation](https://help.form.io/developer/middleware/). What am I missing here?

**Comment by jeriah-formio** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
