### ISSUE TITLE
Error: getaddrinfo ENOTFOUND formio.forms.example.com

### ISSUE THREAD

**Issue by speedlight** [formio/cli#26]
When trying to run `deploy` or `migrate` commands I'm getting the error:
```sh
Error: getaddrinfo ENOTFOUND formio.forms.example.com
```
This is an on-premise formio environment, the url is i.e forms.example.com and the objective is to migrate a portal project (in portal.form.io) to an on-premise project but the script is adding the `formio` subdomain when trying to autheticate to the destination.

A workaround to this was to put an entry to the IP of the on-premise portal in `/etc/hosts` pointing to a domain with the `formio` part:
```sh
123.456.789.12	formio.forms.example.com
```
This way the destination authetication works and the deploy/migrate step starts. Is there a way to avoid the need to add the `/etc/hosts` entry?

**Comment by travist** [comment]
It is attempting to authenticate with the "Portal Base" project in that environment and the default behavior is to use the "formio" subdomain. To resolve this, you can create an API Key on both your source project and your destination project and then use the ```--src-key``` and ```--dst-key``` parameters when performing the migration.

**Comment by speedlight** [comment]
Great thanks, that's solved the issue.
