### ISSUE TITLE
[BUG] Error running deploy command

### ISSUE THREAD

**Issue by speedlight** [formio/cli#27]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [x] On-premise environment
  - [ ] Local deployment
    - Version: 
- Formio.js version: 7.0.0-rc46

## Steps to Reproduce
1. Run
 `./bin/formio deploy --src-username USER --src-password PASSWORD --username USERNAME --password PASSWORD https://portal.form.io/project/5e861xxxxx20ec06daxxx5f2/ https://forms.example.com/project/5fa465b7bxxx9c7689xxxxd7/`

## Expected behavior
The deploy command finish sucessufly 

## Observed behavior
The following error:
```sh
Authenticating to https://form.io
Authentication successful

This action requires a login to DESTINATION::https://forms.example.com.

Authenticating to https://forms.example.com
Authentication successful
Exporting Template
Error: <html>
<head><title>404 Not Found</title></head>
<body>
<h1>404 Not Found</h1>
<ul>
<li>Code: NoSuchKey</li>
<li>Message: The specified key does not exist.</li>
<li>Key: project/5e8618469020xxx6da7xxxf2/export</li>
<li>RequestId: E4291F33333C167C</li>
<li>HostId: GhyHVmVqTxEKAVexxxxxxxxMmG+CHMVVUNTJKJ54vi+cF4xxxxxxxxxqrHnmMCpwjPK3+js=</li>
</ul>
<hr/>
</body>
</html>
```

## Steps to Reproduce
If the web URL is used (notice the `\#/` part added):
`./bin/formio deploy --src-username USERNAME --src-password PASSWORD --username USERNAME --password PASSWORD https://portal.form.io/\#/project/xxxx18469020ec06daxxxxxx/ https://forms.example.com//\#/project/xxxxx5b7b39c9c7689xxxxxx/`

## Observed behavior
The following error:
```sh
This action requires a login to SOURCE::https://form.io#/project/xxxxxx469020ec06daxxxxxx/.

Authenticating to https://form.io#/project/xxxxxx469020ec06daxxxxxx/
Authentication successful

This action requires a login to DESTINATION::https://forms.example.com/#/project/5fa465b7b39c9c76893345d7/.

Authenticating to https://forms.example.com#/project/5fa465b7b39c9c76893345d7/
Authentication successful
Exporting Template
Importing Template
Updating Project
Error: Unexpected token " in JSON at position 0
```

**Comment by travist** [comment]
The URL's should not be the application URL's but rather the API URL's like so.

```formio deploy .....  https://myproject.form.io https://forms.example.com/myproject```

**Comment by speedlight** [comment]
Thanks, now I'm getting the following:
```sh
This action requires a login to SOURCE::https://form.io.
An API Key was provided. Authenticated as Project Owner.


This action requires a login to DESTINATION::https://forms.example.com.
An API Key was provided. Authenticated as Project Owner.

Exporting Template
Importing Template
Updating Project
Error: [object Object]
```

The project stage was just created and only the API key was generated.

**Comment by travist** [comment]
This seems to be throwing an error when importing the project. Try manually exporting the project (using the developer portal) and then importing it into your new project and see if the error you receive is more verbose?

**Comment by jeriah-formio** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
