### ISSUE TITLE
[BUG] Error running migrate command

### ISSUE THREAD

**Issue by horeapopa** [formio/cli#29]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [x] On-premise environment
  - [ ] Local deployment
    - Version: 
        - docker image: 7.0.0-rc.57 
        - formio cli: 1.8.2
        - node version: v15.0.1
        - OS: MacOS 10.15.7 (19H15)

## Steps to Reproduce
1.  run
formio migrate https://project-x.form.io project https://forms.example.com/project-x --src-key API_KEY --dst-key API_KEY

## Expected behavior

The migrate command finish sucessufly

## Observed behavior

Migration fails with exception / error:

➜  ~ formio migrate https://project-x.form.io project https://forms.example.com/project-x --src-key API_KEY --dst-key API_KEY

(node:46702) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
  __  __                          _       __
 / / / _| ___  _ __ _ __ ___     (_) ___  \ \
/ / | |_ / _ \| '__| '_ ` _ \    | |/ _ \  \ \
\ \ |  _| (_) | |  | | | | | | _ | | (_) | / /
 \_\|_|  \___/|_|  |_| |_| |_|(_)|_|\___/ /_/

Welcome to the Form.io Command Line!

  - Help: https://help.form.io
  - Code: https://github.com/formio
  - Love: https://form.io

This action requires a login to SOURCE::https://form.io.
An API Key was provided. Authenticated as Project Owner.

This action requires a login to DESTINATION::https://example.com.
An API Key was provided. Authenticated as Project Owner.

Migrating to https://forms.example.com/project-x/admin
Migrating to https://forms.example.com/project-x/admin/login
Migrating to https://forms.example.com/project-x/csite........../usr/local/lib/node_modules/formio-cli/node_modules/async/dist/async.js:318
            if (fn === null) throw new Error("Callback was already called.");
                             ^

Error: Callback was already called.
    at /usr/local/lib/node_modules/formio-cli/node_modules/async/dist/async.js:318:36
    at Transformer.<anonymous> (/usr/local/lib/node_modules/formio-cli/src/migrate.js:152:16)
    at Transformer.emit (node:events:327:20)
    at finish (node:internal/streams/writable:734:10)
    at processTicksAndRejections (node:internal/process/task_queues:80:21)

**Comment by travist** [comment]
We will take a look. Thanks.

**Comment by jeriah-formio** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
