### ISSUE TITLE
bootstraping application outputs bad request

### ISSUE THREAD

**Issue by biswanaths** [formio/cli#3]
Hey, 

I was trying to bootstrap an formion app using the following command. 

formio bootstrap formio/formio-app-todo 
formio bootstrap formio/formio-app-formio 

I am getting bad request after I have enter the authentication information.  Can you guys help me with this error ?

**Comment by travist** [comment]
Hello @biswanaths. I should have some time tonight to figure out what the errors are.  Thanks for reporting!

**Comment by biswanaths** [comment]
If it helps this is the response I am getting from the api. 

When I fire this 

`var response = formio.authenticate('biswanath@......', '12345678').then(function() {
       console.log("done"); })
`

**Response** 

```
{ state: 'rejected',
  reason: 
   { [Error: Bad Request]
     original: null,
     response: 
      Response {
        domain: [Object],
        _events: {},
        _eventsCount: 0,
        _maxListeners: undefined,
        res: [Object],
        request: [Object],
        req: [Object],
        links: {},
        text: '"Unique fields cannot be empty."',
        body: 'Unique fields cannot be empty.',
        files: {},
        buffered: true,
        headers: [Object],
        header: [Object],
        statusCode: 400,
        status: 400,
        statusType: 4,
        info: false,
        ok: false,
        redirect: false,
        clientError: true,
        serverError: false,
        error: [Object],
        accepted: false,
        noContent: false,
        badRequest: true,
        unauthorized: false,
        notAcceptable: false,
        forbidden: false,
        notFound: false,
        charset: 'utf-8',
        type: 'application/json',
        setEncoding: [Function: bound ],
        redirects: [] },
     status: 400 } }

```

Username and password both are valid, I assume as I can login from the portal.

**Comment by travist** [comment]
Thanks for your help! That did help a lot.  I was able to figure out the issue and pushed up a new version of the cli tool. Please try again by reinstalling with the following.

```
npm install -g formio-cli
```
