### ISSUE TITLE
Copy form is thorwing an error

### ISSUE THREAD

**Issue by arajsh03** [formio/cli#9]
Hi All,
I'm trying to copy a form from one application to another application using formio copy command on my machine. it was throwing error message as below.
Error: getaddrinfo ENOTFOUND formio.localhost formio.localhost:3001

the command I'm running as
 'formio copy  form  http://localhost:3001/#/form/OwnersApp   http://localhost:3000/OwnersApp'.

Please let me know if anyone knows the solution?
Appreciated for the quick response. 

thanks, Raj

**Comment by travist** [comment]
As of right now, the copy command only works for connecting to the Form.io hosted domain. If you wish to copy a form within the localhost domain, then I would recommend using POSTMAN to get the form, and then post it to the new form location.

Hope this helps,

Travis.

**Comment by thsures** [comment]
Hi Travis,
can u help on how to get and post the form using post man to local host domain..like using post man how can copy form to my local host domain?


Thanks
Suresh

**Comment by pageza** [comment]
Hi Suresh, 
For a more timely response please route your support requests to support@form.io or zach@form.io . To answer your question I have some documentation on how to use Postman with your Form.io Project for you here:
https://documenter.getpostman.com/view/684631/formio-api/2Jvuks 
Additionally, we offer support packages that can be utilized for training, code-review or custom development. This time can be spent in one hour increments at your discretion over a 6 month period for training, code-review or development.
 
Hourly rate                  $175.00 per hour
10 hour package         $ 1,500
20 hour package         $ 2,500

Let me know if you would like to connect on a support package, or if I can assist further.
Thanks!--Zach

**Comment by travist** [comment]
I just tested the CLI command here and it is working as designed. In your command, it seems you were trying to copy the portal URL instead of copying the API endpoint for the form. I believe it should have been as follows.

```
formio copy form http://localhost:3001/OwnersApp http://localhost:3001/OwnersApp2
```

which is the OSS API for forms. If you are on our enterprise, then you will need to include the Project names.

```
formio copy form https://localhost:3001/sourceproject/formA https://localhost:3001/destproject
```
